CREATE TABLE IF NOT EXISTS public.thac_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  showroom TEXT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  date TEXT NOT NULL,
  location TEXT,
  brands TEXT[] DEFAULT '{}',
  budget NUMERIC(10, 2) DEFAULT 0,
  leads INT DEFAULT 0,
  gdtd INT DEFAULT 0,
  deals INT DEFAULT 0,
  test_drives INT DEFAULT 0,
  end_date TEXT,
  budget_spent NUMERIC(10, 2) DEFAULT 0,
  leads_actual INT DEFAULT 0,
  gdtd_actual INT DEFAULT 0,
  deals_actual INT DEFAULT 0,
  test_drives_actual INT DEFAULT 0,
  status TEXT DEFAULT 'upcoming',
  priority TEXT DEFAULT 'medium',
  owner TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bật RLS
ALTER TABLE public.thac_events ENABLE ROW LEVEL SECURITY;

-- Cho phép CRUD qua anon key hoặc service_role key
-- Create
DROP POLICY IF EXISTS "Enable insert for all users" ON public.thac_events;
CREATE POLICY "Enable insert for all users" ON public.thac_events FOR INSERT WITH CHECK (true);

-- Read
DROP POLICY IF EXISTS "Enable read access for all users" ON public.thac_events;
CREATE POLICY "Enable read access for all users" ON public.thac_events FOR SELECT USING (true);

-- Update
DROP POLICY IF EXISTS "Enable update for all users" ON public.thac_events;
CREATE POLICY "Enable update for all users" ON public.thac_events FOR UPDATE USING (true);

-- Delete
DROP POLICY IF EXISTS "Enable delete for all users" ON public.thac_events;
CREATE POLICY "Enable delete for all users" ON public.thac_events FOR DELETE USING (true);
